In [1]:
#PROGRAM4
import numpy as np
a=list(map(int,input().split()))
b=list(map(int,input().split()))
c=np.array(a).reshape(3,3)
d=np.array(b).reshape(3,3)
print(c-d)

1 2 3 4 5 6 7 8 9
1 1 1 1 1 1 1 1 1 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
