In [1]:
#PROGRAM 1
import numpy as np
lst=[]
lst1=[]
m=int(input("Enter value of M:"))
n=int(input("Enter value of N:"))
a=int(input("Enter value of A:"))
p=m*n
q=n*a
print("Enter elements of first array")
for i in range(0,p):
    ele=int(input())
    lst.append(ele)
d=np.array(lst).reshape(m,n)
print("Enter elements of second array")
for j in range(0,q):
    ele1=int(input())
    lst1.append(ele1)
c=np.array(lst1).reshape(n,a)
print("FIRST ARRAY:\n",d)
print("SECOND ARRAY:\n",c)
print("DOT PRODUCT OF TWO ARRAYS:\n",np.dot(d,c))




Enter value of M:5
Enter value of N:3
Enter value of A:2
Enter elements of first array
1
2
3
4
5
6
7
8
9
10
11
12
13
141
15
Enter elements of second array
12
13
23
24
24
23
FIRST ARRAY:
 [[  1   2   3]
 [  4   5   6]
 [  7   8   9]
 [ 10  11  12]
 [ 13 141  15]]
SECOND ARRAY:
 [[12 13]
 [23 24]
 [24 23]]
DOT PRODUCT OF TWO ARRAYS:
 [[ 130  130]
 [ 307  310]
 [ 484  490]
 [ 661  670]
 [3759 3898]]
