In [23]:
#Program 3
import numpy as np
a=int(input())
b=int(input())
x=np.arange(1,a*16,a)#a*16 since in 4,4 matrix there will be 16 elements so the end number will be within it with step of a
y=np.arange(1,b*16,b)
r=x.reshape(4,4)
p=y.reshape(4,4)
s=r-p
print("FIRST ARRAY\n",r)
print("SECOND ARRAY\n",p)
print("SUBTRACTED ARRAY\n",s)
print("FLATTENED ARRAY\n",s.flatten())

7
9
FIRST ARRAY
 [[  1   8  15  22]
 [ 29  36  43  50]
 [ 57  64  71  78]
 [ 85  92  99 106]]
SECOND ARRAY
 [[  1  10  19  28]
 [ 37  46  55  64]
 [ 73  82  91 100]
 [109 118 127 136]]
SUBTRACTED ARRAY
 [[  0  -2  -4  -6]
 [ -8 -10 -12 -14]
 [-16 -18 -20 -22]
 [-24 -26 -28 -30]]
FLATTENED ARRAY
 [  0  -2  -4  -6  -8 -10 -12 -14 -16 -18 -20 -22 -24 -26 -28 -30]
